---
- name: Uninstall Nginx
  hosts: lampstack
  become: true

  tasks:
    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped
        enabled: no

    - name: Uninstall Nginx package
      yum:
        name: nginx
        state: absent

