---
- name: Deploy Simple Web Application
  hosts: lampstack
  become: true
  vars:
    nginx_conf_template: /home/vagrant/simplewebsite/templates/nginx.conf.j2
    website_files_directory: /home/vagrant/simplewebsite/files/
    server_name: 192.168.56.2

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Copy Nginx configuration file
      template:
        src: "{{ nginx_conf_template }}"
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart nginx

    - name: Copy website files
      synchronize:
        src: "{{ website_files_directory }}"
        dest: /usr/share/nginx/html
        delete: yes

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

